### ISSUE TITLE
Add the flash and notice banners in the application layouts

### ISSUE THREAD

**Issue by icyflame** [icyflame/networking-rails#22]
@aniarya82 : Assigned to you.

**Comment by aniarya82** [comment]
its already added

On Fri, Apr 24, 2015 at 11:25 PM, Siddharth Kannan <notifications@github.com
> wrote:

> @aniarya82 <https://github.com/aniarya82> : Assigned to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/icyflame/networking-rails/issues/22>.
>



-- 

*Regards,*

*Hiten Chowdhary*

*Undergraduate Student*

*Department of Mathematics*

*IIT Kharagpur*

*Ph: +919800111032*

**Comment by icyflame** [comment]
Fixed by @aniarya82 
Closing this!
