### ISSUE TITLE
Create the student member profile page

### ISSUE THREAD

**Issue by icyflame** [icyflame/networking-rails#4]

**Comment by icyflame** [comment]
Moved closer to the solution of this issue after implementing tie alumni with studmem and solving issue #2.

Now, simply have to show all the alumni with a link to their profile page, on the student's profile page.

**Comment by aniarya82** [comment]
this file is in views > student_member > show.html.erb .....right..???

**Comment by icyflame** [comment]
@aniarya82 
Currently, there's no navbar.

There are just two `navbar-justified-pills` in the `layouts/application.html.erb` file.

You need to change that into a full navbar. once you put it in the navbar, it will appear everywhere. Also, you have to manage the options that are shown depending on who is signed in, etc.

**Comment by icyflame** [comment]
@aniarya82 
Yes! :smile:

**Comment by icyflame** [comment]
@aniarya82

You need to show a table consisting the brief details of all the alumni assigned to the student member who is signed in. (Include the status variables, and name, hall, department. That should be fine. Also, include a serial number as the first column. )
