### ISSUE TITLE
Change navbar style to bootstrap navbar

### ISSUE THREAD

**Issue by icyflame** [icyflame/networking-rails#9]

**Comment by aniarya82** [comment]
I could work on this, once i get this one up and running in my localhost..!!

**Comment by icyflame** [comment]
@aniarya82 
Great! :smile: 
Putting this up on Heroku!

**Comment by icyflame** [comment]
@aniarya82 
Are you facing any problems?
(You shouldn't, because your environment is setup for the most part! Including the `pg` gem, if I am not wrong?)

**Comment by aniarya82** [comment]
i am trying now..!!

**Comment by aniarya82** [comment]
localhost up and running but where is the navigation bar..??
